#!/bin/sh

test -e

check () {
	if ! which -s $1; then
		echo ":-( Couldn't find '$1' on \$PATH"
		echo

		cat

		exit 1
	fi
}

depends () {
	check bundle <<-ERR
Try:

  $ gem install bundler
	ERR
}

setup () {
	bundle install \
		--binstubs \
		--without=production

	bin/sequel -m migrations sqlite://development.db
}

depends && setup && echo OK
